ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ me.lukeforit.blueprint.kmp.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcURL = "jdbc:postgresql://localhost:5432/blueprint_db"
    jdbcURL = ${?DB_URL}
    user = "blueprint_user"
    user = ${?DB_USER}
    password = "blueprint_password"
    password = ${?DB_PASSWORD}
}
